import type { Workspace } from '../../domain/atlas'
import { flattenProjects } from '../../domain/atlas'
import type { DispatchState } from '../../domain/dispatch'
import type { AtlasCalibrationState } from '../../domain/calibration'

const TEMPLATE_HEADERS = [
  'kind',
  'targetId',
  'projectId',
  'runbookId',
  'artifactId',
  'preservePathId',
  'verificationCheckId',
  'remoteHost',
  'remoteUser',
  'remoteFrontendPath',
  'remoteBackendPath',
  'publicUrl',
  'healthCheckUrls',
  'databaseName',
  'credentialRef',
  'repository',
  'label',
  'provider',
  'purpose',
  'notes',
  'targetIds',
  'projectIds',
  'summary',
  'status',
  'verificationCadence',
  'nextAction',
  'lastMeaningfulChange',
  'lastVerified',
  'currentRisk',
  'blockers',
  'deferredItems',
  'notDoingItems',
  'decisions',
  'backupCadence',
  'backupLocationRef',
  'rollbackReference',
  'rollbackSteps',
  'maintenanceWindow',
  'escalationContactRef',
  'lastReviewedAt',
  'filename',
  'role',
  'sourceRepo',
  'targetPath',
  'required',
  'onlyWhenFullAppReady',
  'checksum',
  'inspectedAt',
  'warnings',
  'path',
  'reason',
  'temporary',
  'method',
  'urlPath',
  'expectedStatuses',
  'protectedResource',
]

function csvEscape(value: string) {
  return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value
}

function templateRow(values: Record<string, string>) {
  return TEMPLATE_HEADERS.map((header) => values[header] ?? '')
}

export function createCalibrationCsvTemplate(dispatch: DispatchState) {
  const rows = [
    ...dispatch.targets.map((target) =>
      templateRow({
        kind: 'dispatch-target',
        targetId: target.id,
        projectId: target.projectId,
        remoteHost: target.remoteHost,
        remoteUser: target.remoteUser,
        remoteFrontendPath: target.remoteFrontendPath,
        remoteBackendPath: target.remoteBackendPath,
        publicUrl: target.publicUrl,
        healthCheckUrls: target.healthCheckUrls.join('|'),
        databaseName: target.databaseName,
        credentialRef: target.credentialRef,
      }),
    ),
    ...dispatch.recoveryPlans.map((plan) =>
      templateRow({
        kind: 'recovery-plan',
        targetId: plan.targetId,
        projectId: plan.projectId,
        backupCadence: plan.backupCadence,
        backupLocationRef: plan.backupLocationRef,
        rollbackReference: plan.rollbackReference,
        rollbackSteps: plan.rollbackSteps.join('|'),
        maintenanceWindow: plan.maintenanceWindow,
        escalationContactRef: plan.escalationContactRef,
        lastReviewedAt: plan.lastReviewedAt,
        notes: plan.notes.join('|'),
      }),
    ),
    ...dispatch.runbooks.flatMap((runbook) => [
      ...runbook.artifacts.map((artifact) =>
        templateRow({
          kind: 'runbook-artifact',
          targetId: runbook.targetId,
          projectId: runbook.projectId,
          runbookId: runbook.id,
          artifactId: artifact.id,
          filename: artifact.filename,
          role: artifact.role,
          sourceRepo: artifact.sourceRepo,
          targetPath: artifact.targetPath,
          required: String(artifact.required),
          onlyWhenFullAppReady: String(artifact.onlyWhenFullAppReady),
          checksum: artifact.checksum,
          inspectedAt: artifact.inspectedAt,
          warnings: artifact.warnings.join('|'),
          notes: artifact.notes.join('|'),
        }),
      ),
      ...runbook.preservePaths.map((preservePath) =>
        templateRow({
          kind: 'runbook-preserve-path',
          targetId: runbook.targetId,
          projectId: runbook.projectId,
          runbookId: runbook.id,
          preservePathId: preservePath.id,
          path: preservePath.path,
          reason: preservePath.reason,
          required: String(preservePath.required),
          temporary: String(preservePath.temporary),
          notes: preservePath.notes.join('|'),
        }),
      ),
      ...runbook.verificationChecks.map((check) =>
        templateRow({
          kind: 'runbook-verification-check',
          targetId: runbook.targetId,
          projectId: runbook.projectId,
          runbookId: runbook.id,
          verificationCheckId: check.id,
          label: check.label,
          method: check.method,
          urlPath: check.urlPath,
          expectedStatuses: check.expectedStatuses.join('|'),
          protectedResource: String(check.protectedResource),
          notes: check.notes.join('|'),
        }),
      ),
    ]),
  ]

  return [TEMPLATE_HEADERS, ...rows].map((row) => row.map(csvEscape).join(',')).join('\n')
}

export function createCalibrationJsonTemplate(
  workspace: Workspace,
  dispatch: DispatchState,
  calibration: AtlasCalibrationState,
) {
  return JSON.stringify(
    {
      rows: [
        ...dispatch.targets.map((target) => ({
          kind: 'dispatch-target',
          targetId: target.id,
          projectId: target.projectId,
          remoteHost: target.remoteHost,
          remoteUser: target.remoteUser,
          remoteFrontendPath: target.remoteFrontendPath,
          remoteBackendPath: target.remoteBackendPath,
          publicUrl: target.publicUrl,
          healthCheckUrls: target.healthCheckUrls.join('|'),
          databaseName: target.databaseName,
          credentialRef: target.credentialRef,
        })),
        ...flattenProjects(workspace).map((record) => ({
          kind: 'project-manual',
          projectId: record.project.id,
          summary: record.project.summary,
          status: record.project.manual.status,
          verificationCadence: record.project.manual.verificationCadence,
          nextAction: record.project.manual.nextAction,
          lastMeaningfulChange: record.project.manual.lastMeaningfulChange,
          lastVerified: record.project.manual.lastVerified,
          currentRisk: record.project.manual.currentRisk,
          blockers: record.project.manual.blockers.join('|'),
          deferredItems: record.project.manual.deferredItems.join('|'),
          notDoingItems: record.project.manual.notDoingItems.join('|'),
          notes: record.project.manual.notes.join('|'),
          decisions: record.project.manual.decisions.join('|'),
        })),
        ...flattenProjects(workspace).map((record) => ({
          kind: 'repo-binding',
          projectId: record.project.id,
          repository: record.project.repositories[0]
            ? `${record.project.repositories[0].owner}/${record.project.repositories[0].name}`
            : '',
        })),
        ...calibration.credentialReferences.map((reference) => ({
          kind: 'credential-reference',
          label: reference.label,
          provider: reference.provider,
          purpose: reference.purpose,
          notes: reference.notes,
          targetIds: reference.targetIds.join('|'),
          projectIds: reference.projectIds.join('|'),
        })),
        ...dispatch.recoveryPlans.map((plan) => ({
          kind: 'recovery-plan',
          targetId: plan.targetId,
          projectId: plan.projectId,
          backupCadence: plan.backupCadence,
          backupLocationRef: plan.backupLocationRef,
          rollbackReference: plan.rollbackReference,
          rollbackSteps: plan.rollbackSteps.join('|'),
          maintenanceWindow: plan.maintenanceWindow,
          escalationContactRef: plan.escalationContactRef,
          lastReviewedAt: plan.lastReviewedAt,
          notes: plan.notes.join('|'),
        })),
        ...dispatch.runbooks.flatMap((runbook) => [
          ...runbook.artifacts.map((artifact) => ({
            kind: 'runbook-artifact',
            targetId: runbook.targetId,
            projectId: runbook.projectId,
            runbookId: runbook.id,
            artifactId: artifact.id,
            filename: artifact.filename,
            role: artifact.role,
            sourceRepo: artifact.sourceRepo,
            targetPath: artifact.targetPath,
            required: String(artifact.required),
            onlyWhenFullAppReady: String(artifact.onlyWhenFullAppReady),
            checksum: artifact.checksum,
            inspectedAt: artifact.inspectedAt,
            warnings: artifact.warnings.join('|'),
            notes: artifact.notes.join('|'),
          })),
          ...runbook.preservePaths.map((preservePath) => ({
            kind: 'runbook-preserve-path',
            targetId: runbook.targetId,
            projectId: runbook.projectId,
            runbookId: runbook.id,
            preservePathId: preservePath.id,
            path: preservePath.path,
            reason: preservePath.reason,
            required: String(preservePath.required),
            temporary: String(preservePath.temporary),
            notes: preservePath.notes.join('|'),
          })),
          ...runbook.verificationChecks.map((check) => ({
            kind: 'runbook-verification-check',
            targetId: runbook.targetId,
            projectId: runbook.projectId,
            runbookId: runbook.id,
            verificationCheckId: check.id,
            label: check.label,
            method: check.method,
            urlPath: check.urlPath,
            expectedStatuses: check.expectedStatuses.join('|'),
            protectedResource: String(check.protectedResource),
            notes: check.notes.join('|'),
          })),
        ]),
      ],
    },
    null,
    2,
  )
}
